DROP TABLE kysely;
DROP TABLE kysymys;
DROP TABLE vaihtoehto;

CREATE TABLE kysely (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nimi VARCHAR(250) NOT NULL,
kuvaus LONG NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE kysymys (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
teksti VARCHAR(250) NOT NULL,
monivalinta BOOLEAN,
kysely_id SMALLINT NOT NULL,
CONSTRAINT fk_kysely_id FOREIGN KEY (kysely_id) REFERENCES kysely (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE vaihtoehto (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
teksti VARCHAR(250) NOT NULL,
kysymys_id SMALLINT NOT NULL,
CONSTRAINT fk_kysymys_id FOREIGN KEY (kysymys_id) REFERENCES kysymys (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
