CREATE TABLE kysely (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nimi VARCHAR(250) NOT NULL,
kuvaus LONG NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE kysymys (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
teksti VARCHAR(250) NOT NULL,
monivalinta BOOLEAN,
kysely_id SMALLINT NOT NULL,
CONSTRAINT fk_kysely_id FOREIGN KEY (kysely_id) REFERENCES kysely (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE vaihtoehto (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
teksti VARCHAR(250) NOT NULL,
kysymys_id SMALLINT NOT NULL,
CONSTRAINT fk_kysymys_id FOREIGN KEY (kysymys_id) REFERENCES kysymys (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE vastaus (
id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
teksti LONG NOT NULL,
kysymys_id SMALLINT NOT NULL,
CONSTRAINT fk_kysymys FOREIGN KEY (kysymys_id) REFERENCES kysymys (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE rooli (
  id SMALLINT NOT NULL auto_increment PRIMARY KEY,
  rooli VARCHAR(255) NOT NULL UNIQUE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 CREATE TABLE kayttaja (
  id SMALLINT NOT NULL auto_increment PRIMARY KEY,
  kayttaja VARCHAR(255) NOT NULL UNIQUE,
  salasana VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE kayttaja_rooli (
  id SMALLINT NOT NULL auto_increment PRIMARY KEY,
  kayttaja_id SMALLINT NOT NULL,
  rooli_id SMALLINT NOT NULL,
  FOREIGN KEY (kayttaja_id) REFERENCES kayttaja(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (rooli_id) REFERENCES rooli(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
